function renderPage() {
    generateDefault();
    document.getElementById("content").setAttribute("style", "margin-left:10%")
    ignoreNoBootstrapNotice();
    var boot = new Bootstrap();
    var navigation = new boot.Navbar("navi");
    var brand = new navigation.Brand();
    var text = new A();
    text.setId("bcr");
    text.setText("Made with bootstrap, jQuery and GBLib");
    text.setStyle("color:grey;display:inline");
    brand.setName(document.title);
    brand.brand.getAPI().style.color="white";
    navigation.setDark();
    navigation.setBrand(brand);
    navigation.create("navigation");
    addSpacer("content");
    var p = new P();
    p.addSpacing();
    p.addSpacing();
    p.addSpacing();
    p.addSpacing();
    p.addSpacing();
    p.addSpacing();
    p.addSpacing();
    p.addSpacing();
    p.addSpacing();
    p.addSpacing();
    p.addSpacing();
    p.addSpacing();
    p.getAPI().append(text.getAPI());
    p.addSpacing();
    p.addSpacing();
    var moreinfotext = new A();
    moreinfotext.setText("For more information click ");
    var moreinfo = new A();
    moreinfo.setText("here");
    moreinfo.setTarget("_blank");
    moreinfo.setHref("https://www.w3.org/TR/2012/WD-html-markup-20121025/elements.html");
    p.getAPI().append(moreinfotext.getAPI());
    p.getAPI().append(moreinfo.getAPI());
    p.create();
    var line = new Line();
    line.create();
    addSpacer("content");
    addSpacer("content");
    var center = new boot.CenterDiv();
    var h2 = new H("2");
    h2.setText("Documentation for GBLib - WIP");
    center.getAPI().append(h2.getAPI());
    center.create("content");
    addSpacer("content");
    addSpacer("content");
    var elements = new Div();
    elements.setId("elements");
    elements.create("content");
    addSpacer("elements");
    addSpacer("elements");
    var ele = new H("3");
    ele.setText("Elements");
    ele.create("elements")
    var button = new H("4");
    button.setText("Button");
    button.setId("button");
    elements.getAPI().append(button.getAPI());
    var buttondesc = new TextArea();
    buttondesc.setText(buttondescription);
    buttondesc.setReadonly();
    buttondesc.setStyle("resize:none;width:80%;height:730px");
    elements.getAPI().append(buttondesc.getAPI());
    addSpacer("elements");
    var buttonexample = new Div();
    buttonexample.setId("buttonexample");
    var buttonexampleiframe = new iFrame();
    buttonexampleiframe.setSrcDoc("<!DOCTYPE html><html><head><script src='http://werwolf2303.de/GBLib/main.js'></script></head><body onload='render()'><script>function render() {var button = new Button();button.setText('Example Button');button.create();}</script></body></html>");
    buttonexampleiframe.getAPI().setAttribute("style", "border-style:solid;border-color:grey");
    buttonexample.getAPI().append(buttonexampleiframe.getAPI());
    var buttonexamplecode = new TextArea();
    buttonexamplecode.setReadonly();
    buttonexamplecode.setStyle("resize:none;width:90%;height:120px");
    buttonexamplecode.setText("var button = new Button();\nbutton.setText('Example Button');\nbutton.create();");
    var buttonexamplecodetext = new A();
    buttonexamplecodetext.setText("Example Code:");
    buttonexample.getAPI().append(buttonexamplecodetext.getAPI());
    buttonexample.getAPI().append(buttonexamplecode.getAPI());
    buttonexample.setStyle("border-style:solid;width:80%");
    buttonexample.create("elements");
    addSpacer("elements");
    addSpacer("elements");
    var div = new H("4");
    div.setText("Div");
    div.setId("div");
    elements.getAPI().append(div.getAPI());
    var divdesc = new TextArea();
    divdesc.setText(divdescription);
    divdesc.setReadonly();
    divdesc.setStyle("resize:none;width:80%;height:180px");
    elements.getAPI().append(divdesc.getAPI());
    addSpacer("elements");
    var divexample = new Div();
    divexample.setId("divexample");
    var divexamplecode = new TextArea();
    divexamplecode.setReadonly();
    divexamplecode.setStyle("resize:none;width:90%;height:120px;display:inline");
    divexamplecode.setText("var div = new Div();\ndiv.create();");
    var divexamplecodetext = new A();
    divexamplecodetext.setText("Example Code:");
    divexample.getAPI().append(divexamplecodetext.getAPI());
    divexample.getAPI().append(divexamplecode.getAPI());
    divexample.setStyle("border-style:solid;width:80%");
    divexample.create("elements");
    addSpacer("elements");
    addSpacer("elements");
    var iframe = new H("4");
    iframe.setText("iFrame");
    elements.getAPI().append(iframe.getAPI());
    var iframedesc = new TextArea();
    iframedesc.setText(iframedescription);
    iframedesc.setReadonly();
    iframedesc.setStyle("resize:none;width:80%;height:210px");
    elements.getAPI().append(iframedesc.getAPI());
    addSpacer("elements");
    var iframeexample = new Div();
    iframeexample.setId("iframeexample");
    var iframeexampletext = new A();
    iframeexampletext.setText("YouTube Embedded via iFrame");
    iframeexample.getAPI().append(iframeexampletext.getAPI());
    var iframeexampleiframe = new iFrame();
    iframeexampleiframe.setSrcDoc("<!DOCTYPE html><html><head><script src='http://werwolf2303.de/GBLib/main.js'></script></head><body onload='render()'><script>function render() {var frame = new iFrame();frame.setSrc('https://www.youtube.com/embed/mR8FsJi-8cs');frame.create();}</script></body></html>");
    iframeexampleiframe.getAPI().setAttribute("style", "width:320px;height:200px;border-style:solid;border-color:grey");
    iframeexample.getAPI().append(iframeexampleiframe.getAPI());
    var iframeexamplecode = new TextArea();
    iframeexamplecode.setReadonly();
    iframeexamplecode.setStyle("resize:none;width:90%;height:120px");
    iframeexamplecode.setText("var frame = new iFrame();\nframe.setSrc('https://www.youtube.com/embed/mR8FsJi-8cs');\nframe.create();");
    var iframeexamplecodetext = new A();
    iframeexamplecodetext.setText("Example Code:");
    iframeexample.getAPI().append(iframeexamplecodetext.getAPI());
    iframeexample.getAPI().append(iframeexamplecode.getAPI());
    iframeexample.setStyle("border-style:solid;width:80%");
    iframeexample.create("elements");
    addSpacer("elements");
    addSpacer("elements");
    addSpacer("elements");
    var tools = new H("3");
    tools.setText("Tools and Features");
    tools.create("elements");
    var encryption = new H("4");
    encryption.setText("Self made encryption and decryption");
    encryption.create("elements");
    var encryptionexample = new Div();
    encryptionexample.setId("encryptionexample");
    var encryptiondesc = new TextArea();
    encryptiondesc.setReadonly();
    encryptiondesc.setStyle("resize:none;width:80%;height:60px");
    encryptiondesc.setText(encryptiondescription);
    encryptiondesc.create("elements");
    var encryptionexampleiframe = new iFrame();
    encryptionexampleiframe.setSrcDoc("<!DOCTYPE html><html><head><script src='http://werwolf2303.de/GBLib/main.js'></script></head><body onload='render()'><script>function render() {var readable = new A();readable.setText('Readable: ' + 'Hello World');readable.create();document.body.innerHTML+='<br>';var encrypted = new A();encrypted.setText('Encrypted: ' + new Toolkits().encryptString('Hello World', 99));encrypted.create();}</script></body></html>");
    encryptionexampleiframe.getAPI().setAttribute("style", "width:320px;height:200px;border-style:solid;border-color:grey");
    encryptionexample.getAPI().append(encryptionexampleiframe.getAPI());
    var encryptionexamplecode = new TextArea();
    encryptionexamplecode.setReadonly();
    encryptionexamplecode.setStyle("resize:none;width:90%;height:120px");
    encryptionexamplecode.setText("Encryption: new Toolkits().encryptString(string, secnumber);\nDecryption: new Toolkits().decryptString(string, secnumber);");
    var encryptionexamplecodetext = new A();
    encryptionexamplecodetext.setText("Example Code:");
    encryptionexample.getAPI().append(encryptionexamplecodetext.getAPI());
    encryptionexample.getAPI().append(encryptionexamplecode.getAPI());
    encryptionexample.setStyle("border-style:solid;width:80%");
    encryptionexample.create("elements");
    addSpacer("elements");
    var colors = new H("4");
    colors.setText("Colors");
    colors.create("elements");
    var colorstext = new TextArea();
    colorstext.setText(colorsdescription);
    colorstext.setReadonly();
    colorstext.setStyle("resize:none;width:80%;height:1380px");
    colorstext.create("elements");
    addSpacer("elements");
}
var colorsdescription = 'this.GlobalContrastBase = "#3F5161";\nthis.BrandOrHighlight = "#427CAC";\nthis.ContrastHighlight = "#91C8F6";\nthis.GlobalLightBase = "#EFF4F9";\nthis.Containers = "#FFFFFF";\nthis.ApplicationContentBackground = "#FAFAFA";\nthis.BordersAndDerivedControls = "#BFBFBF";\nthis.TitlesAndTexts = "#333333";\nthis.LaunchPadContrastTop = "#2C4E6C";\nthis.LaunchPadContrastBottom = "#9EC7D8";\nthis.LaunchPadLightTop = "#A9C6DE";\nthis.LaunchPadLightBottom = "#E7ECF0";\nthis.Accent1 = "#E09D00";\nthis.Accent2 = "#E6600D";\nthis.Accent3 = "#C14646";\nthis.Accent4 = "#AB218E";\nthis.Accent5 = "#678BC7";\nthis.Accent6 = "#0092D1";\nthis.Accent7 = "#1A9898";\nthis.Accent8 = "#759421";\nthis.Accent9 = "#925ACE";\nthis.Accent10 = "#647987";\nthis.Grayscale0 = "#333333";\nthis.Grayscale1 = "#666666";\nthis.Grayscale2 = "#BFBFBF";\nthis.Grayscale3 = "#CCCCCC";\nthis.Grayscale4 = "#E5E5E5";\nthis.Grayscale5 = "#FFFFFF";\nthis.SemanticNegative = "#BB0000";\nthis.SemanticCritical = "#E78C07";\nthis.SemanticPositive = "#2B7D2B";\nthis.SemanticNeutral = "#5E696E";\nthis.SemanticInformation = "#427cac";\nthis.SemanticDarkFlavorNegative = "#FF8888";\nthis.SemanticDarkFlavorCritical = "#FABD64";\nthis.SemanticDarkFlavorPositive = "#ABE2AB";\nthis.SemanticDarkFlavorNeutral = "#D3D7D9";\nthis.SemanticDarkFlavorInformation = "#91c8f6";\nthis.IndicationLight1 = "#880000";\nthis.IndicationLight2 = "#bb0000";\nthis.IndicationLight3 = "#E78C07";\nthis.IndicationLight4 = "#2B7C2B";\nthis.IndicationLight5 = "#427CAC";\nthis.IndicationLight6 = "#1a9898";\nthis.IndicationLight7 = "#925ace";\nthis.IndicationLight8 = "#ab218e";\nthis.IndicationDark1 = "#FF8888";\nthis.IndicationDark2 = "#FFBBBB";\nthis.IndicationDark3 = "#FABD64";\nthis.IndicationDark4 = "#ABE2AB";\nthis.IndicationDark5 = "#91c8f6";\nthis.IndicationDark6 = "#7fc6c6";\nthis.IndicationDark7 = "#b995e0";\nthis.IndicationDark8 = "#e269c9";\nthis.AppleBlack = "#000000";\nthis.AppleGray = "#949494";\nthis.AppleBlue = "#2997FF";';
var encryptiondescription = "encryptString(string, secnumber) - Encrypts the string multiplied by the secnumber\ndecryptString(string, secnumber) - Decrypts the string divided by the secnumber";
var iframedescription = "setSrc(src) - Sets the url to render\nsetSrcDoc(html) - Sets the html to render\nsetStyle(style) - Sets the style of the iframe\nsetClass(class) - Sets the class of the iframe\nsetId(id) - Sets the id of the iframe\ngetAPI - Gets the raw document\ncreate(at) - Creates the element inside of the element with the id\ncreate - Creates the element inside of the body";
var divdescription = "setId(id) - Sets the id of the div\nsetClass(class) - Sets the class of the div\nsetStyle(style) - Sets the style of the div\ngetAPI - Gets the raw element\nsetClick(functionname) - Sets what happens when clicked inside div\ncreate(at) - Creates the element inside element of id\ncreate - Creates the element inside the body";
var buttondescription = "setId(id) - Sets the id of the button\nsetClass(name) - Sets the class of the button\nsetClick(functionname) - Sets what happens when clicked\nsetText(text) - Sets the button text\nsetForm(form) - WIP\nsetFormAction(url) - WIP\nsetDisabled - Sets button unclickable(greyed out)\nsetAutoFocus - WIP\nsetFormEncType(type) - WIP\nsetFormMethod(method) - WIP\nsetFormNoValidate - WIP\nsetFormTarget(target) - WIP\nsetName(name) - Sets the name of the button\nsetType(type) - Sets the type of the button\nsetValue(value) - Sets the value of the button\nsetAccessKey(key) - Sets the access key of the button\nsetContentEditable - WIP\nsetData(data) - Sets the date of the button\nsetDir(dir) - WIP\nsetDraggable - WIP\nsetHidden - WIP\nsetLang(lang) - WIP\nsetSpellCheck - WIP\nsetStyle(style) - Sets the style of the button\nsetTabIndex(tabindex) - Sets the tabindex of the button\nsetTitle(title) - Sets the title of the button\nsetTranslate - WIP\ngetAPI - Gets the raw document\ncreate(to) - Creates the element inner specific element with id\ncreate - Creates the element at body";
